[tool.towncrier]
directory = "changelog.d"
filename = "CHANGES.md"
name = "Changes in Element X"
template = "tools/towncrier/template.md"
issue_format = "[#{issue}](https://github.com/vector-im/element-x-android/issues/{issue})"

[[tool.towncrier.type]]
directory = "feature"
name = "Features âœ¨"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bugfixes ğŸ›"
showcontent = true

[[tool.towncrier.type]]
directory = "wip"
name = "In development ğŸš§"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Improved Documentation ğŸ“š"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Other changes"
showcontent = true
