name: Sync Localazy
on:
  schedule:
    # At 00:00 on every Monday UTC
    # - cron: '0 0 * * 1'
    - cron: '0/10 * * * *'

jobs:
  sync-localazy:
    runs-on: ubuntu-latest
    # Skip in forks
    if: github.repository == 'vector-im/element-x-android'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Setup Localazy
        run: |
          curl -sS https://dist.localazy.com/debian/pubkey.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/localazy.gpg
          echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/localazy.gpg] https://maven.localazy.com/repository/apt/ stable main" | sudo tee /etc/apt/sources.list.d/localazy.list
          sudo apt-get update && sudo apt-get install localazy
      - name: Run Localazy script
        run: ./tools/localazy/downloadStrings.sh --all
      - name: Create Pull Request for Strings
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Sync Strings from Localazy
          title: Sync Strings
          body: |
            - Update Strings from Localazy
          branch: sync-localazy
          base: develop
